global:
  smtp_smarthost: "mail:1025"
  smtp_require_tls: false
  smtp_from: "Alertmanager <alert_from@example.com>"

route:
  receiver: "mailtest"
  group_by: ["alertname", "instance", "severity"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 10m

receivers:
  - name: "mailtest"
    email_configs:
      - to: "kazuyo.rikudo@gmail.com"
