# config file for prometheus

# global config
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert.rules

alerting:
  alertmanagers:
    - follow_redirects: true
      enable_http2: true
      scheme: http
      timeout: 10s
      static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "fastapi"
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ["fastapi:8000"]
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets:
          - localhost:9090
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9003"]
  - job_name: "mail"
    static_configs:
      - targets: ["mail:8025"]
